### ISSUE TITLE
If user is not allowed to log work, they should not see any reference to time worked by others

### ISSUE THREAD

**Issue by fdiebel** [EMRL/chrono#12]
This functionality would make it so we could have clients be able to login and see their tasks, but I don't want them see actual work time spent on tasks.

We could probably use the project permission "Work" to achieve this. Clients would not have permission to work on tasks, and so time worked would be hidden, Or something.

This kinda seems like a bug or oversight in the original code, it shoulda been like this outta the box if you ask me.

**Comment by joehorning** [comment]
I will be getting together with Corey on this when time permits.
